"""PostgreSQL-backed repository for generated quiz artifacts."""
from __future__ import annotations

import asyncio
from typing import Optional

from sqlalchemy.orm import Session, sessionmaker

from ..db_models import QuizArtifactRecord
from ..models.quiz_artifact import QuizArtifact


class QuizArtifactRepository:
    """Retrieve quiz artifacts generated by the Study Engine."""

    def __init__(self, session_factory: sessionmaker[Session]) -> None:
        self._session_factory = session_factory

    async def _run(self, func, *args, **kwargs):
        return await asyncio.to_thread(func, *args, **kwargs)

    async def get_quiz(self, quiz_id: str) -> Optional[QuizArtifact]:
        def _get() -> Optional[QuizArtifact]:
            session: Session = self._session_factory()
            try:
                record = session.get(QuizArtifactRecord, quiz_id)
                if record is None:
                    return None
                payload = {
                    "quizId": record.quiz_id,
                    "provider": record.provider,
                    "noteId": record.note_id,
                    "appId": record.app_id,
                    "userId": record.user_id,
                    "sessionId": record.session_id,
                    "questionCount": record.question_count,
                    "requestedQuestionCount": record.requested_question_count,
                    "requestedQuestionTypes": record.requested_question_types,
                    "questionTypes": record.question_types,
                    "includeReflection": record.include_reflection,
                    "questions": record.questions or [],
                    "reflection": record.reflection,
                    "metadata": record.metadata_json or {},
                    "createdAt": record.created_at,
                    "updatedAt": record.updated_at,
                }
                return QuizArtifact(**payload)
            finally:
                session.close()

        return await self._run(_get)
