"""SQLAlchemy ORM models for the Study Engine."""
from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func

from .config import settings
from .database import Base


class QuizArtifactRecord(Base):
    """Persisted quiz artifact generated by the Study Engine."""

    __tablename__ = settings.quiz_artifacts_table

    quiz_id = Column(String, primary_key=True, nullable=False)
    provider = Column(String, nullable=True)
    note_id = Column(String, nullable=True, index=True)
    app_id = Column(String, nullable=True, index=True)
    user_id = Column(String, nullable=True, index=True)
    session_id = Column(String, nullable=True, index=True)
    question_count = Column(Integer, nullable=True)
    requested_question_count = Column(Integer, nullable=True)
    requested_question_types = Column(JSONB, nullable=True)
    question_types = Column(JSONB, nullable=True)
    include_reflection = Column(Boolean, nullable=True)
    questions = Column(JSONB, nullable=False, default=list)
    reflection = Column(JSONB, nullable=True)
    metadata_json = Column("metadata", JSONB, nullable=False, default=dict)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
    updated_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now())

    def __repr__(self) -> str:  # pragma: no cover - debugging helper
        return f"QuizArtifactRecord(quiz_id={self.quiz_id!r}, provider={self.provider!r})"
